### PR TITLE
Resolve #22, #20

### LINKED ISSUE #20: Expects a workspace path
Screen Shot 2022-04-21 at 12 07 54 AM

Pressing ⇧⌘N opens windows that aren't associated to any folder, and opening a JavaScript file in one of those windows prompts the extension to crash.

The little arrow shown in the screenshot leads you to the following lines of code. I think `join` is throwing when `workspacePath` is nullish.

```JS
const workspacePath = nova.workspace.path;
const denoConfigPath = nova.path.join(workspacePath, "deno.json");
const configWatcher = nova.fs.watch(denoConfigPath, () => {
  taskDisposable.dispose();
  taskDisposable.add(registerDenoTasks());
  nova.commands.invoke("co.gwil.deno.commands.restartServer");
});
```

The solution might simply be to skip those lines if there's no `workspace.path` :).  Unfortunately, there seems to be similar code elsewhere; solving this issue could be a little harder.

### LINKED ISSUE #22: Auto-detect deno.jsonc configs
Right now tasks are derived from deno.json files, but we don't detect deno.jsonc (JSON with comment) config files.

### PR DESCRIPTION
**Pull request by belcar-s**
This pull request resolves #22 and resolves #20.

This is my first substantial contribution to someone else's software, so please be patient and forgive any issues 🙂.

These changes enable the use of the extension in project-less windows:
Screen Shot 2022-04-30 at 1 23 32 PM

Except during editing of unsaved documents 🙁:
Screen Shot 2022-04-30 at 1 35 37 PM

They also cause tasks defined in `deno.jsonc` files to be displayed inside the Tasks menu:

Screen Shot 2022-04-30 at 1 25 47 PM

I used the `strip-json-comments` NPM module to parse _JSON with comments_ files, and tried to mimic the way `vscode-languageserver-types` was imported.

### CODE REVIEW

File: deps.ts [hunk 1]
```diff
@@ -1 +1,2 @@
 export * as lsp from "https://cdn.skypack.dev/vscode-languageserver-types?dts";
+export { default as stripJSONcomments } from "https://cdn.skypack.dev/strip-json-comments?dts";
```
Comment (belcar-s) [inline deps.ts:2]: I don't know what the inclusion of `?dts` does. Sorry if it's not necessary.

Comment (sgwilym) [reply deps.ts:2]: ?dts is a way of telling Skypack to provide Typescript typings when transforming this NPM package to ESM.

**Review by sgwilym — APPROVED** [review]
> This is my first substantial contribution to someone else's software, so please be patient and forgive any issues 🙂.

Congratulations! And thanks for choosing this project.

It all looks good to me.

**Comment by sgwilym** [comment]
Released in v1.0.4!
